config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  get '/journey/:id/like', to: 'journeys#like', as: 'like'

  resources :profiles, only: [:show]
  resources :journeys do
    resources :steps, only: [:create]
  end
  resources :steps, only: [:destroy]
  get "lines/search", to: "lines#search"

  mount Sidekiq::Web => '/sidekiq'
end

app/models/journey.rb
class Journey < ApplicationRecord
  belongs_to :user
  belongs_to :station_start, class_name: 'Station', inverse_of: :journeys_as_station_start
  belongs_to :station_end, class_name: 'Station', inverse_of: :journeys_as_station_end

  has_many :steps, -> { order("position ASC") }, dependent: :destroy
  has_many :cities
  has_many :activities
  has_many :likes, dependent: :destroy

  has_one_attached :photo

  def total_distance
    distances = self.steps.map do |step|
      step.distance
    end
    distances.sum
  end
end

app/controllers/journeys_controller.rb
class JourneysController < ApplicationController
  include JourneyMapHelper
  include GeojsonHelper

  before_action :authenticate_user!, except: :show
  before_action :set_journey, only: %i[show edit update destroy like]

  def index
    @journeys = Journey.where(user: current_user)
  end

  def show
  end

  def create
    @station_start = Station.find(journey_params[:station_start_id])
    @journey = Journey.new(
      station_start: @station_start,
      station_end: @station_start,
      user: current_user,
      duration: 0,
      name: "New trip from #{@station_start.city.name.capitalize}!"
    )
    if @journey.save!
      redirect_to edit_journey_path(@journey)
    else
      render "pages/home", status: :unprocessable_entity
    end
  end

  def edit
    data = build_map_data(@journey)

    @selected_stations = data[:selected_stations]
    @reachable_stations = data[:reachable_stations]
    @trip_lines = data[:trip_lines]
    @existing_lines = data[:existing_lines]
    @stations = @journey.steps
                        .includes(line: :station_end)
                        .select { |step| step.kind == "line" }
                        .map { |step| step.line.station_end }
                        .unshift(@journey.station_start)
    @steps_lines = data[:steps_lines]
    @steps_stays = data[:steps_stays]
    @current_station = data[:current_station]

    @current_step_id = @journey.steps.present? ? @journey.steps.last.id : ""
  end

  def update
    @journey.name = journey_params[:name]
    @journey.photo.attach(journey_params[:photo]) unless journey_params[:photo].blank?

    respond_to do |format|
      if @journey.save
        format.html { render :show, locals: { journey: @journey } }
        format.json { render json: {}, status: :ok }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: {}, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @journey.destroy
    redirect_to journeys_path
  end

  def like
    @journey_like = @journey.likes.find_by(user_id: current_user)
    if @journey_like
      @journey_like.destroy
    else
      new_like = Like.create(user_id: current_user.id, journey_id: @journey.id)
      @journey.likes << new_like
    end
    redirect_to journeys_path
  end

  private

  def journey_params
    params.require(:journey).permit(:station_start_id, :name, :photo)
  end

  def set_journey
    @journey = Journey.includes(steps: :line).find(params[:id])
  end
end

app/helpers/journey_helper.rb
module JourneyHelper
  def duration_for(journey)
    journey_in_hours = journey.duration / 60
    journey_in_days = journey_in_hours / 24

    minutes = "minutes"
    minutes = "minute" if (journey.duration % 60) < 2

    hours = "hours"
    hours = "hour" if journey_in_hours < 2

    modulo_hours = "hours"
    modulo_hours = "hour" if (journey_in_hours % 24) < 2

    days = "days"
    days = "day" if journey_in_days < 2

    if journey_in_hours < 24
      "<strong>#{journey_in_hours}</strong> #{hours} and <strong>#{journey.duration % 60}</strong> #{minutes}"
    else
      "<strong>#{journey_in_days}</strong> #{days} and <strong>#{journey_in_hours % 24}</strong> #{modulo_hours}"
    end
  end
end

app/views/journeys/_loader.html.erb
<div data-journey-target="loader" class="train-background d-none">
  <p class="train-text">
    Saving your map...
  </p>
  <div class= "train-loader">
    <div class="train"></div>
    <div class="track">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>
</div>

app/views/journeys/_sidebar.html.erb
<div class="sidebar">
  <div class="d-flex align-items-center flex-grow-1">
    <i class="fa-solid fa-pencil"></i>
    <%= simple_form_for @journey, html: { class: "flex-grow-1", data: { journey_target: "journeyForm" } } do |f| %>
      <%= f.input_field :name, class: "journey-name", data: { journey_target: "nameInput", action: "keyup->journey#autosave" } %>
      <%= f.input_field :photo, as: :file, class: "d-none", data: { journey_target: "photoInput" } %>
    <% end %>
  </div>
  <button data-action="click->journey#validateJourney" class="btn btn-secondary btn-sm rounded-pill">Validate journey</button>
</div>

app/views/journeys/_station_list.html.erb
<ul class="station-list" data-journey-target="stations">
  <li><%= journey.station_start.name %></li>
  <% journey.steps.each do |step| %>
    <% if step.kind == "line" %>
      <li>
        <%= step.line.station_end.name %>
        <a href="#" data-action="click->journey#removeStepFromJourney" data-journey-step-id-param="<%= step.id %>">
          <i class="fa-solid fa-trash"></i>
        </a>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/journeys/_stay_modal.html.erb
<div class="modal fade" id="stayModal" tabindex="-1" aria-labelledby="Add a stay" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-sm">
    <div class="modal-content">
      <div class="modal-body">
        <%= form_with url: journey_steps_path(journey), method: :post, data: { action: "submit->journey#addStayStepToJourney" } do |form| %>
          <%= form.label :duration, "How many days?", class: "form-label" %>
          <%= form.number_field :duration, value: 2, in: 1..90, class: "form-control mb-3", data: { journey_target: "durationInput" } %>
          <%= form.number_field :station_id, class: "d-none", data: { journey_target: "stationInput" } %>
          <%= button_tag(type: "submit", class: "btn btn-primary mb-3") do %>
            <i class="fa-solid fa-check"></i> Add
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/journeys/_ticket.html.erb
<% if step.kind == "line" %>
  <div
    class="ticket-wrap"
    data-action="mouseenter->journey#toggleLineHighlight mouseleave->journey#toggleLineHighlight"
    data-journey-step-id-param="<%= step.line.id %>">
    <% unless readonly %>
      <div class="delete-btn">
        <a href="#" data-action="click->journey#removeStepFromJourney" data-journey-step-id-param="<%= step.id %>">
          <i class="fa-solid fa-trash"></i>
        </a>
      </div>
    <% end %>
    <div class='ticket-concatenation'>
      <div class="ticket-left-banner">
        <svg width="16" height="130" viewBox="0 0 16 130" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M16 130H0L0 73C0 73 8 72.8788 8 65C8 57.1212 0 57 0 57L0 0H16L16 51.2121C16 51.2121 16 57.1212 16 65C16 72.8788 16 78.2955 16 78.2955L16 130Z" fill="white"/>
        </svg>
      </div>
      <div class="ticket ticket-line">
        <div class="ticket-top">
          <div class="ticket-city-start">
            <p class="ticket-city-name"><strong><%= step.line.station_start.city.name.upcase.truncate(12) %></strong></p>
            <p class="ticket-text-small"><%= step.line.station_start.name.truncate(13) %></p>
          </div>
          <div class="ticket-logo">
            <svg xmlns="http://www.w3.org/2000/svg" width="78" height="28" fill="none" viewBox="0 0 78 28">
              <path stroke="#E6612F" stroke-dasharray="2 2" stroke-linecap="round" d="M8.926 14.089h13.947M52.409 14.089h16.665"/>
              <circle cx="37.641" cy="13.909" r="13.409" fill="#fff" stroke="#E6612F"/>
              <circle cx="5.029" cy="13.909" r="3.897" fill="#fff" stroke="#E6612F"/>
              <circle cx="72.971" cy="13.909" r="3.897" fill="#fff" stroke="#E6612F"/>
              <path fill="#E6612F" d="M37.01 7.794h-5.484v5.941h.002v6.48H46.65v-1.62h-1.63c1.354 0 2.117-1.552 1.284-2.619l-1.814-2.24v4.86h-3.78l-.667-.862a3.376 3.376 0 0 0-2.677-1.299h-5.3v-2.7H44.49l-.938-1.08h-.002l-.003-.004-2.816-3.236a5.092 5.092 0 0 0-3.72-1.62Zm3.303 1.956.097.114 2.425 2.79h-6.87a3.181 3.181 0 0 1-2.558-1.295l-.671-.908c-.314-.426-.01-1.036.517-1.036h6.256c.33 0 .593.092.804.335Z"/>
              <path fill="#E6612F" d="M42.875 15.895h-1.08a.542.542 0 0 1-.54-.54c0-.297.243-.54.54-.54h1.08c.297 0 .54.243.54.54 0 .297-.243.54-.54.54Z"/>
            </svg>
          </div>
          <div class="ticket-city-end">
            <p class="ticket-city-name"><strong><%= step.line.station_end.city.name.upcase.truncate(12) %></strong></p>
            <p class="ticket-text-small"><%= step.line.station_end.name.truncate(13) %></p>
          </div>
        </div>
        <div class="ticket-dotted-line"></div>
        <div class="ticket-bottom">
          <div class="ticket-data">
            <p class="ticket-text-small text-distance">Distance</p>
            <p style="font-size:14px"><strong><%= step.distance %></strong>km</p>
          </div>
          <div class="ticket-data">
            <p class="ticket-text-small text-duration">Duration </p>
            <p style="font-size:14px"><strong><%= step.duration / 60 %></strong>h<strong><%= (step.duration % 60).to_s.rjust(2, '0') %>
              </strong></p>
          </div>
          <% if readonly == true %>
            <% if step.line %>
              <%= link_to "Go!", "https://www.thetrainline.com/book/results?origin=#{step.line.station_start.trainline}&destination=#{step.line.station_end.trainline}&outwardDate=2023-06-#{Time.now.day + 1}T12%3A00%3A00&outwardDateType=departAfter&journeySearchType=single&passengers%5B%5D=1996-06-14%7Ca15a8ad9-39a3-4d09-883f-a93c85c55e0f&directSearch=false&lang=en-us&selectedOutward=bJH5BqRpjq0%3D%3AKw2IL6ITjO8%3D%3AStandard", target: '_blank', class:'btn btn-outline-primary book-button' %>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="ticket-right-banner">
        <svg width="16" height="130" viewBox="0 0 16 130" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M0 0H16V57C16 57 8 57.1212 8 65C8 72.8788 16 73 16 73V130H0V78.7879C0 78.7879 0 72.8788 0 65C0 57.1212 0 51.7045 0 51.7045V0Z" fill="white"/>
        </svg>
      </div>
    </div>
  </div>
<% else %>
  <div class="ticket-wrap">
    <% unless readonly %>
      <div class="delete-btn">
        <a href="#" data-action="click->journey#removeStepFromJourney" data-journey-step-id-param="<%= step.id %>">
          <i class="fa-solid fa-trash"></i>
        </a>
      </div>
    <% end %>
    <div class="ticket ticket-stay">
      <% if step.stay.city.photo.present? %>
        <div class="ticket-bg" style="background-image: url('<%= cl_image_path step.stay.city.photo.key %>')"></div>
      <% else %>
        <div class="ticket-bg"></div>
      <% end %>
      <div class="stay-header">
        <div class="stay-city"><%= step.stay.city.name.upcase %></div>
        <div class="stay-country"> <%= step.stay.city.country %></div>
      </div>
      <div class="stay-duration">
        <i class="fa-regular fa-clock"></i>
        <%= step.stay.duration / 60 / 24 %> days
      </div>
    </div>
  </div>
<% end %>

app/views/journeys/_tickets.html.erb
<div class="tickets-container">
  <div class="<%= class_names('d-flex', 'align-items-center', { 'd-none': journey.steps.empty? }) %>" data-journey-target="ticketsHeader">
  </div>
  <div class="tickets" data-journey-target="tickets">
    <% journey.steps.each do |step| %>
      <%= render "ticket", step: step, readonly: false %>
    <% end %>
  </div>
</div>

app/views/journeys/edit.html.erb
<% content_for :head do %>
  <meta name="turbo-visit-control" content="reload">
<% end %>
<div class="map-side-bar">
  <div
    data-controller="journey"
    data-journey-target="map"
    data-journey-selected-stations-value="<%= @selected_stations %>"
    data-journey-reachable-stations-value="<%= @reachable_stations %>"
    data-journey-existing-lines-value="<%= @existing_lines %>"
    data-journey-trip-lines-value="<%= @trip_lines %>"
    data-journey-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
    data-journey-journey-value="<%= @journey.to_json %>"
    data-journey-stations-value="<%= @stations.to_json %>"
    data-journey-current-station-value="<%= @current_station %>"
    data-journey-current-step-id-value="<%= @current_step_id %>"
    data-journey-steps-lines-value="<%= @steps_lines.to_json %>"
    data-journey-steps-stays-value="<%= @steps_stays.to_json %>"
    >
    <div id="journey-map"></div>
    <%= render "loader" %>
    <%= render "sidebar", journey: @journey %>
    <%= render "tickets", journey: @journey %>
    <%= render "stay_modal", journey: @journey %>
  </div>
</div>

app/views/journeys/index.html.erb
<div class="container pt-5">
  <h1 class="text-center fw-bold mb-5 text-light">Take a look at your journeys</h1>
  <ul id="journeys" class="list-unstyled row row-cols-lg-auto g-5">
    <% @journeys.each do |journey| %>
      <li class="col">
        <%= link_to journey_path(journey), class: "text-decoration-none text-black" do %>
          <div class="card h-100">
            <div>
              <% if journey.photo.attached? %>
                <%= image_tag journey.photo, crop: :fill, class: "card-img-top" %>
              <% else %>
                <%= image_tag "https://images.winalist.com/blog/wp-content/uploads/2021/02/26144939/shutterstock_535048540-scaled.jpg", crop: :fill, class: "card-img-top" %>
              <% end %>
            <% end %>
          </div>
          <div class="card-body">
            <div class="d-flex justify-content-between">
              <h5 class="card-title fw-bold"><%= journey.name %></h5>
              <span>
                <%= link_to like_path(journey), method: 'patch' do %>
                  <i class="fas fa-heart" style="color: #ff0000;"></i>
                <% end %>
                <%= journey.likes.count %>
              </span>
            </div>
            <p class="card-description">
              From <strong><%= journey.station_start.name %></strong> <br>
              to <strong><%= journey.station_end.name %></strong>
            </p>
          </div>
          <div class="card-footer">
            <p> Journey duration: <br>
              <%= duration_for(journey).html_safe %>
            </p>
            <br>
            <%= link_to "Edit", edit_journey_path(journey), class: "btn btn-primary sm" %>
            <%= link_to "Delete this journey", journey_path(journey), class: "btn btn-outline-danger", data: {
                turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= link_to "Homepage", root_path, class: "btn btn-primary sm" %>
</div>

app/views/journeys/show.html.erb
<% content_for :meta_title, "#{@journey.name} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, meta_description %>
<% content_for :meta_image, cl_image_path(@journey.photo.key) if @journey.photo.attached? %>

<div class="bg-color">
  <div class="d-flex space-between row g-0">
    <div class="tickets-list order-2 order-lg-1 col-12 col-lg-5 col-xl-4">
      <div class="d-flex inline-block justify-content-between">
        <span>
          <%= link_to journeys_path, class: "text-white text-decoration-none" do %>
            <i class="fa-solid fa-chevron-left me-2"></i><span class="i-tag-text">Your journeys!</span>
          <% end %>
        </span>
        <span class="align-items-center d-flex justify-content-between">
          <span class="me-2 mt-auto mx-auto">
            <a href="https://twitter.com/share?ref_src=twsrc%5Etfw"
               class="twitter-share-button"
               id="share"
               data-text="Hey! look at my journey on Zenloop!"
               data-hashtags="EcoTrip"
               data-lang="en"
               data-show-count="false">Tweet</a>
            <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
          </span>
          <span class="m-1">
            <%= link_to edit_journey_path, class: "text-decoration-none" do %>
              <i class="fa-solid fa-pencil me-2 i-tag"></i>
            <% end %>
          </span>
          <span class="m-1 mr-0">
            <%= link_to journey_path, class: "text-decoration-none", data: { turbo_method: :delete, turbo_confirm: "Do you really want to delete your journey ?" } do %>
              <i class="fa-solid fa-trash me-2 i-tag"></i>
            <% end %>
          </span>
        </span>
      </div>
      <h1 class="text-center fw-bold"><%= @journey.name.capitalize %></h1>
      <h6 class="text-center text-white">Journey duration : <%= duration_for(@journey).html_safe %> </h6>
      <h6 class="text-center text-white">Journey distance : <%= @journey.total_distance %> km !</h6>
      <div class="tickets" data-journey-target="tickets">
        <% @journey.steps.each do |step| %>
          <%= render "ticket", step: step, readonly: true %>
        <% end %>
      </div>
    </div>
    <div
    class="banner-map order-1 order-lg-2 col-12 col-lg-7 col-xl-8"
    data-controller="screenshot"
    >
      <% if @journey.photo.attached? %>
        <div
        class="screenshot"
        data-screenshot-target="screenshot"
        style="background-image: url('<%= cl_image_path @journey.photo.key %>')"
        data-action="mousemove->screenshot#move"
        >
        </div>
      <% else %>
        <div
        class="screenshot"
        data-screenshot-target="screenshot"
        style="background-image: url('https://images.winalist.com/blog/wp-content/uploads/2021/02/26144939/shutterstock_535048540-scaled.jpg')"
        data-action="mousemove->screenshot#move"
        >
      <% end %>
    </div>
  </div>
</div>